### ISSUE TITLE
AttributeError: 'module' object has no attribute 'descriptors'

### ISSUE THREAD

**Issue by peterbjorgensen** [epfl-cosmo/glosim#5]
Hi,
Thanks for making these algorithms available.
I just downloaded quippy and installed it using this guide https://libatoms.github.io/QUIP/install.html
I checked out your code and tried to run the example, but I get the following trace:

```
python2 glosim.py example/mol-50.xyz
WARNING! fast hungarian library is not available 

Cannot find mcpermanent.so module in pythonpath. Permanent evaluations will be very slow and approximate.
Get it from https://github.com/sandipde/MCpermanent 
          TIME:   Wed Dec 21 17:34:03 2016
        ___  __    _____  ___  ____  __  __ 
       / __)(  )  (  _  )/ __)(_  _)(  \/  )
      ( (_-. )(__  )(_)( \__ \ _)(_  )    ( 
       \___/(____)(_____)(___/(____)(_/\/\_)
                                            
                                             
Reading input file example/mol-50.xyz
50  Configurations Read
Computing SOAPs
Traceback (most recent call last):   
  File "glosim.py", line 871, in <module>
    main(args.filename, nd=args.n, ld=args.l, coff=args.c, cotw=args.cotw, gs=args.g, mu=args.mu, centerweight=args.cw, periodic=args.periodic, usekit=args.usekit, kit=args.kit,alchemyrules=args.alchemy_rules, kmode=args.kernel, nonorm=args.nonorm, permanenteps=args.permanenteps, reggamma=args.gamma, noatom=noatom, nocenter=nocenter, envsim=args.envsim, nprocs=args.np, verbose=args.verbose, envij=envij, prefix=args.prefix, nlandmark=args.nlandmarks, printsim=args.distance,ref_xyz=args.refxyz,partialsim=args.livek,lowmem=args.lowmem,restartflag=args.restart, zeta=args.zeta, xspecies=args.separate_species, alrange=(args.first,args.last), refrange=(args.reffirst, args.reflast))
  File "glosim.py", line 189, in main
    si.parse(at, coff, cotw, nd, ld, gs, centerweight, nocenter, noatom, kit = kit)       
  File "/home/peter/kodesjov/glosim/libmatch/structures.py", line 82, in parse
    desc = quippy.descriptors.Descriptor("soap central_weight="+str(cw)+"  covariance_sigma0=0.0 atom_sigma="+str(gs)+" cutoff="+str(coff)+" cutoff_transition_width="+str(cotw)+" n_max="+str(nmax)+" l_max="+str(lmax)+' '+lspecies+' Z='+str(sp) )   
AttributeError: 'module' object has no attribute 'descriptors'
```

**Comment by peterbjorgensen** [comment]
Found out that `descriptors` is part of the `GAP` (Gaussian Approximation Potential models) package that needs to be compiled into QUIP (and quippy). Now it seems to be working.

**Comment by ceriottm** [comment]
Glad to see you got it working. Get in touch if you need any further help.

**Comment by vishikh** [comment]
I have installed QUIP with GAP, and yet I'm getting the following error  when I tried to use glosim with the example file that has been provided.

```
python ../glosim-master/glosim.py ../glosim-master/example/mol-50.xyz
Cannot find mcpermanent.so module in pythonpath. Permanent evaluations will be very slow and approximate.
Get it from https://github.com/sandipde/MCpermanent 
          TIME:   Tue May 23 12:19:29 2017
        ___  __    _____  ___  ____  __  __ 
       / __)(  )  (  _  )/ __)(_  _)(  \/  )
      ( (_-. )(__  )(_)( \__ \ _)(_  )    ( 
       \___/(____)(_____)(___/(____)(_/\/\_)
                                            
                                             
using output prefix = ../Downloads/Project_SketchMap/glosim-master/example/mol-50-n9-l9-c3.5-g0.3_fastavg_nnrm
Reading input file ../Downloads/Project_SketchMap/glosim-master/example/mol-50.xyz
50  Configurations Read
Computing SOAPs
Traceback (most recent call last):   
  File "../Downloads/Project_SketchMap/glosim-master/glosim.py", line 889, in <module>
    main(args.filename, nd=args.n, ld=args.l, coff=args.c, cotw=args.cotw, gs=args.g, mu=args.mu, centerweight=args.cw, periodic=args.periodic, usekit=args.usekit, kit=args.kit,alchemyrules=args.alchemy_rules, kmode=args.kernel, nonorm=args.nonorm, permanenteps=args.permanenteps, reggamma=args.gamma, noatom=noatom, nocenter=nocenter, envsim=args.envsim, nprocs=args.np, verbose=args.verbose, envij=envij, prefix=args.prefix, nlandmark=args.nlandmarks, printsim=args.distance,ref_xyz=args.refxyz,partialsim=args.livek,lowmem=args.lowmem,restartflag=args.restart, zeta=args.zeta, xspecies=args.separate_species, alrange=(args.first,args.last), refrange=(args.reffirst, args.reflast))
  File "../Downloads/Project_SketchMap/glosim-master/glosim.py", line 209, in main
    si.parse(at, coff, cotw, nd, ld, gs, centerweight, nocenter, noatom, kit = kit) #, soapdump = sys.stdout)       
  File "/home/athavale/Downloads/Project_SketchMap/glosim-master/libmatch/structures.py", line 91, in parse
    desc.calc(at,descriptor_out=psp)
  File "/home/athavale/.local/lib/python2.7/site-packages/quippy/descriptors.py", line 47, in wrapper
    return method(self, at, *args, **kw)
TypeError: calc() got an unexpected keyword argument 'descriptor_out'

```

**Comment by sandipde** [comment]
@vishikh Are you still having the problem ?

**Comment by vishikh** [comment]
The problem was solved. Apparently, I was using an old version of GAP. I downloaded a new version of GAP, and recompiled QUIP.

**Comment by sandipde** [comment]
@vishikh  That makes sense ! Good to know the problem is solved. Let us know if you need any help in future.
